### PR TITLE
Fix unmarshalling of JSON response

### PR DESCRIPTION
**Pull request by jannickfahlbusch**
When a search just returns one result the previous algorithm splitted the JSON not completely which resulted in crashes.

I simplified the unmarshalling by unmarshalling directly into `[]Results` rather than doing it for every entry.

### CODE REVIEW

**Comment by milosb793** [comment]
Hey @jannickfahlbusch, I faced the same error still. I tried to pull the code from your fork. Maybe I'm still doing something wrong.. 
```
➜  crtsh_fix git:(fixJsonEncoding) ✗ ./main search --domain domain.tld
Failed to unmarshal json: unexpected end of JSON input
➜  crtsh_fix git:(fixJsonEncoding) ✗ ./main search --domain %.domain.tld
Failed to send HTTP request: Get https://crt.sh/?output=json&q=%25.domain.tld: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

```

**Comment by jannickfahlbusch** [comment]
That's weird, it worked when I wrote this patch.

Seems like they changed something in their API

Edit: Even weirder is, that it works on my development machine. Can you try to run the program with `go run`?

**Comment by rudSarkar** [comment]
I am going to check tomorrow with this patch.

**Comment by rudSarkar** [comment]
I updated this patch in my repo: https://github.com/rudSarkar/crtsh-by-knqyf263 with the credit of @knqyf263 and thanks to @jannickfahlbusch for the PR.

**Comment by knqyf263** [comment]
I've just noticed this patch now. Thanks.

**Comment by rudSarkar** [comment]
It's been a year 😅😅

**Pull request merged**
